Play travis
Otus-DevOps-2021-02/f4k3lol_infra pull request #3
Opened 2021-04-08 04:04 UTC by f4k3lol

ДЗ4 - интеграция автотестов

2021-04-08 06:25 UTC, mrgreyves requested changes
Здравствуйте!) Оставил вам комментарий к файлу, нужно поправить совсем не много. ДЗ возвращаю на доработку.

2021-04-08 06:25 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Ошибочка закралась =)

2021-04-08 13:42 UTC, f4k3lol commented
Пофиксил

2021-04-09 06:59 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-04-09 06:59 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 2)
🤘🤘🤘

2021-04-09 10:25 UTC, merged