Packer base
Otus-DevOps-2021-02/f4k3lol_infra pull request #5
Opened 2021-04-13 06:58 UTC by f4k3lol

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-04-13 15:30 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Вам следуют свериться с результатами тестов. Не хватает некоторых файлов, дз возвращаю в доработку.

2021-04-13 17:19 UTC, f4k3lol commented
В тесте написано что должен быть вывод 
`Command: cd packer && packer validate -var-file=variables.json.example ubuntu16.json stdout should eq "Template validated successfully.\n"`. 
Но у меня нет вывода, и при этом ошибок тоже нет: ![image](https://user-images.githubusercontent.com/59759737/114593895-0d811680-9ca6-11eb-8cf9-cf6e4e115197.png)

2021-04-14 08:13 UTC, mrgreyves requested changes
Здравствуйте! У вас еще файлов не хватает 
![image](https://user-images.githubusercontent.com/34331259/114676918-74d4b000-9d12-11eb-9666-279ef7cc92cb.png)
Вы целиком смотрели вывод тестов?

2021-04-16 06:22 UTC, f4k3lol commented
Теперь у меня только две ошибки, и обе ругаются на вывод команды. Я про это писал выше

2021-04-16 08:57 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно добавить ваш ключик в репу. Причем ключ должен быть с фейковыми данными, и все будет хорошо. Осталось совсем чуть-чуть =)

2021-04-19 08:40 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комметарий к дз.

2021-04-19 08:40 UTC, mrgreyves commented on packer/variables.json.example
> +    "path_to_keyfile": "/home/nschinnikov/f4k3lol_infra/packer/key2.json"
Вот тут захардкожен путь, попробуйте изменить его на использование например ~ =)

2021-04-19 08:56 UTC, f4k3lol commented on packer/variables.json.example
> +    "path_to_keyfile": "/home/nschinnikov/f4k3lol_infra/packer/key2.json"
у  меня так и было, но была ошибка: 
![image](https://user-images.githubusercontent.com/59759737/115209361-f4012400-a116-11eb-802a-cac5c14d4208.png)

2021-04-22 09:04 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-04-22 10:33 UTC, merged