Terraform 1
Otus-DevOps-2021-02/f4k3lol_infra pull request #6
Opened 2021-04-27 20:55 UTC by f4k3lol

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
Указано в readme.md

## Как запустить проект:
Чтобы запустить нужно выполнить tf apply (настроен alias)

## Как проверить работоспособность:
Взять адрес из output: lb_ip_address, перейти по ссылке http://lb_ip_address/

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-04-29 12:29 UTC, mrgreyves requested changes
Здравствуйте!) Вам стоит ознакомиться с результатами тестов. Некоторых файлов не хватает, так же не везде есть пустые строки в конце файлов. ДЗ возвращаю на доработку.

2021-05-02 16:37 UTC, f4k3lol commented
хоть убейте я не понимаю какой писать путь до файлов, по которым не проходит тест. я пробовал указывать и ~/f4k3lol_infra, и /home/nschinnikov/f4k3lol_infra. Объясните пожалуйста в чем проблема

2021-05-03 18:14 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к фаул. ДЗ возвращаю на доработку.

2021-05-03 18:14 UTC, mrgreyves commented on packer/variables.json.example
> +    "path_to_keyfile": "/home/nschinnikov/key.json"
Попробуйте указать просто key.json, естественно он должен быть в папке =)

2021-05-05 10:38 UTC, mrgreyves requested changes
Здравствуйте!) Давайте дожмем уже эту домашку, осталось совсем чуть-чуть. Поправьте пустые строки в файлах и все будет хорошо =)

2021-05-08 13:21 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь апрув!=)

2021-05-08 14:54 UTC, merged