Ansible 2
Otus-DevOps-2021-02/f4k3lol_infra pull request #9
Opened 2021-06-04 06:43 UTC by f4k3lol

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
Написаны плейбуки сначало в одном сценарии, потом разбиты на сценарии, потом разбиты на файлы. Написаны провиженеры для packer на ansible

## Как запустить проект:
 ansible-playbook site.yml

## Как проверить работоспособность:
 - Выполнить плейбуки, перейти на ссылку http://app-ip:9292

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-06-07 09:24 UTC, mrgreyves requested changes
Здравствуйте!) Проверьте есть ли права на чтение для файла key.json.example =)

2021-06-07 09:40 UTC, f4k3lol commented
4 -rw-r--r-- 1 nschinnikov nschinnikov 2406 Jun  3 21:45 key.json
4 -rw-rw-r-- 1 nschinnikov nschinnikov 2402 May 24 10:08 key.json.example

2021-06-10 15:27 UTC, mrgreyves requested changes
Здравствуйте!) Нужно откорректировать файлы пакера, оставил комментарий к файлу =)

2021-06-10 15:27 UTC, mrgreyves commented on packer/db.json
> +            "playbook_file": "../ansible/packer_db.yml"
Уберите ../ пути не корректные

2021-06-14 17:26 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-06-15 06:18 UTC, merged